# perfil por defecto o local
server:
  port: 7001

logging:
  level:
    root: INFO
    ar.admiral: DEBUG

# agregamos un nuevo perfil para que corra con docker
---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080